---
# This playbook installs knoppix on harddisk on all sites

- name: Setup Knoppix 9.2 on harddisk (please edit config.yml first!) 
  hosts: all
  become: yes 
    #remote_user: root

  roles:
    #- knoppix-partition-check
    #- knoppix-mnt-system-check
    #- knoppix-boot-partition
    - knoppix-copy-system
    - knoppix-autoconfig-patch
    - knoppix-make-KNOPPIX-iso
    - refind-download
    - refind-knoppix-entries
    #- knoppix-grub-menu
    #- knoppix-grub-install
