---
# This playbook installs knoppix on harddisk on all sites

- name: partition an empty harddisk
  hosts: all
  become: yes 
    #remote_user: root

  roles:
    - knoppix-mnt-system-check
    - knoppix-partitions
    - knoppix-copy-system
    - knoppix-autoconfig-patch
    - knoppix-make-KNOPPIX-iso
    - knoppix-grub-menu
    - knoppix-grub-install
