---
# This playbook copies the boot and the KNOPPIX directory to the later
# /mnt-system. Because /mnt-system might still be on the DVD, the new
# version is mounted on /mnt/boot
- name: Mount BOOT on /mnt/boot
  mount: 
    path: /mnt/boot
    src: /dev/{{ boot_disk }}{{ boot_pnum }}
    fstype: reiserfs
    state: mounted

- name: Sync KNOPPIX to /mnt/boot
  synchronize:
    src: /mnt-system/KNOPPIX
    dest: /mnt/boot

# Sync boot only once, because links mess up the second try
- name: Check if boot in /mnt/boot exists
  stat:
    path: /mnt/boot/boot
  register: mnt_boot_boot_stat

- name: Sync /boot to /mnt/boot
  synchronize:
    src: /boot
    dest: /mnt/boot
    copy_links: yes
  when: not mnt_boot_boot_stat.stat.exists

# When booting from harddisk, the syslinux directory is gone
- name: Copy minirt.gz to /mnt/boot
  copy:
    dest: /mnt/boot/boot
    src: /mnt-system/boot/syslinux/minirt.gz
  when: not mnt_boot_boot_stat.stat.exists
