- name: Sync KNOPPIX to /mnt/boot
  synchronize:
    src: /mnt-system/KNOPPIX
    dest: /mnt/boot

- name: Check if boot in /mnt/boot exists
  stat:
    path: /mnt/boot/boot
  register: mnt_boot_boot_stat

- name: Sync /boot to /mnt/boot
  synchronize:
    src: /boot
    dest: /mnt/boot
    copy_links: yes
  when: not mnt_boot_boot_stat.stat.exists


- name: Copy minirt.gz to /mnt/boot
  copy:
    dest: /mnt/boot/boot
    src: /mnt-system/boot/syslinux/minirt.gz
  when: mnt_system_fstype == "iso9660"
