---
# This playbook partitions a clean harddisk with knoppix partitions
#

- name: Create boot partition
  parted:
    device: /dev/sda
    number: 1
    #name: boot
    part_end: 5121MiB
    state: present

- name: Format boot partition
  filesystem:
    device: /dev/sda1
    fstype: reiserfs
    state: present

- name: Create /mnt directory 
  file:
    path: /mnt
    state: directory

- name: Link /mnt/boot to /mnt-system (if /mnt-system already from disk)
  file:
    src: /mnt-system
    dest: /mnt/boot
    state: link
  when: mnt_system_fstype == "reiserfs"

- name: Create boot mount point
  file:
    path: /mnt/boot
    state: directory
  when: mnt_system_fstype == "iso9660"

- name: Mount boot partition
  mount:
    path: /mnt/boot
    src: /dev/sda1
    fstype: reiserfs
    state: mounted
  when: mnt_system_fstype == "iso9660"

      #- name: Create conf partition
      #  parted:
      #    device: /dev/sda
      #    number: 2
      #    #name: conf
      #    part_start: 5121MiB
      #    part_end: 5633MiB
      #    state: present

      #- name: Format conf partition
      #  filesystem:
      #    device: /dev/sda2
      #    fstype: ext4
      #    state: present

      #- name: Create conf mount point
      #  file:
      #    path: /mnt/conf
      #    state: directory

      #- name: Mount conf partition
      #  mount:
      #    path: /mnt/conf
      #    src: /dev/sda2
      #    fstype: ext4
      #    state: mounted

      #- name: Create data partition
      #  parted:
      #    device: /dev/sda
      #    number: 3
      #    #name: conf
      #    part_start: 5633MiB
      #    part_end: 26113MiB
      #    state: present

      #- name: Format data partition
      #  filesystem:
      #    device: /dev/sda3
      #    fstype: ext4
      #    state: present

      #- name: Create conf mount point
      #  file:
      #    path: /mnt/data
      #    state: directory

      #- name: Mount data partition
      #  mount:
      #    path: /mnt/data
      #    src: /dev/sda3
      #    fstype: ext4
      #    state: mounted

