- name: Install grub package
  apt:
    name: grub
    state: present

- name: Scan block devices
  command: 'lsblk -J'
  register: results

- debug:
    var: results.stdout.blockdevices

- name: Install grub on boot sector
  shell:
    cmd: grub-install --recheck --root-directory=/mnt/boot /dev/sda
