- name: Install jmespath 
  pip:
    name: jmespath 
    state: present

#- name: Install python3-apt
#  apt:
#    name: python3-apt
#    state: present
#    update_cache: yes

#- name: Install grub package
#  apt:
#    name: grub-legacy
#    state: present
#    update_cache: yes

- name: Scan block devices
  command: 'lsblk -fJ'
  register: results

- name: Analyze block devices
  set_fact:
#+    blockdevices: "{{ results.stdout | from_json }}"
#+    blockdevices: "{{ results.stdout | from_json | json_query('*') }}"
#+    blockdevices: "{{ results.stdout | from_json | json_query('blockdevices[]') }}"
#+    blockdevices: "{{ results.stdout | from_json | json_query('blockdevices[].children') }}"
#+    blockdevices: "{{ results.stdout | from_json | json_query('blockdevices[].children[*].mountpoint') }}"
    mnt_system_fstype: "{{ results.stdout | from_json | json_query(\"blockdevices[].children[?mountpoint == '/mnt-system'].fstype[] | [0]\") }}"
#-    blockdevices: "{{ results.stdout | from_json | json_query('blockdevices[]') | json_query('*') }}"

- debug:
    var: mnt_system_fstype

- name: Install grub on boot sector
  shell:
    cmd: grub-install --recheck --root-directory=/mnt-system /dev/sda
  when: mnt_system_fstype == "reiserfs"
