#- name: Install python3-apt
#  apt:
#    name: python3-apt
#    state: present
#    update_cache: yes

#- name: Install grub package
#  apt:
#    name: grub-legacy
#    state: present
#    update_cache: yes

- name: Install grub on boot sector
  shell:
    cmd: grub-install --recheck --root-directory=/mnt-system /dev/sda
  when: mnt_system_fstype == "reiserfs"
